// <auto-generated />
namespace TestingSystem.DataBaseConfigurations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_database_new_answer_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_database_new_answer_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201606181423108_new_database_new_answer_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
