// <auto-generated />
namespace TestingSystem.DataBaseConfigurations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_base_new_migration_new : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_base_new_migration_new));
        
        string IMigrationMetadata.Id
        {
            get { return "201606171832309_new_base_new_migration_new"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
