// <auto-generated />
namespace TestingSystem.DataBaseConfigurations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_moigration_for_check : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_moigration_for_check));
        
        string IMigrationMetadata.Id
        {
            get { return "201606161511121_new_mo=igration_for_check"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
