// <auto-generated />
namespace TestingSystem.DataBaseConfigurations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_one_booblyk_huj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_one_booblyk_huj));
        
        string IMigrationMetadata.Id
        {
            get { return "201606141821264_initial_one_booblyk_huj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
