// <auto-generated />
namespace TestingSystem.DataBaseConfigurations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _new_database_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_new_database_));
        
        string IMigrationMetadata.Id
        {
            get { return "201606181526169__new_database_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
